id: PBFD30BDC
initial_creation_type: ocr
source_metadata:
  volumes:
    230cb9db202a41a1826545dced642a13:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: གཏན་ཚིགས་ཀྱི་འཁོར་ལོ་གཏན་ལ་དབབ་པ།
      total_pages: 1198
      volume_number: 97
